"""
Export a fresh Douyin cookie file for the production gateway.

The script opens an isolated browser profile, waits for Douyin cookies to appear,
and writes a Netscape-format cookie file that yt-dlp can consume. It avoids
reading the user's normal Chrome cookie database, which is often locked or
encrypted by modern Chromium builds.

Usage:
    python scripts/export-douyin-cookie.py --output 抖音cookie.txt
"""

from __future__ import annotations

import argparse
import datetime as dt
import io
import sys
import time
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

try:
    from playwright.sync_api import sync_playwright
except ImportError as exc:  # pragma: no cover - operational script
    raise SystemExit("缺少 Python Playwright：请先安装 playwright 并执行 playwright install chromium") from exc


DOUYIN_URL = "https://www.douyin.com/"
COOKIE_DOMAINS = ("douyin.com", "iesdouyin.com", "douyincdn.com", "amemv.com")
IMPORTANT_COOKIE_NAMES = {
    "__ac_nonce",
    "msToken",
    "passport_csrf_token",
    "s_v_web_id",
    "sessionid",
    "sessionid_ss",
    "tt_scid",
    "ttwid",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="抖音cookie.txt", help="输出 Netscape cookie 文件路径")
    parser.add_argument("--url", default=DOUYIN_URL, help="打开的抖音页面，可传入具体视频链接")
    parser.add_argument(
        "--profile-dir",
        default="output/douyin-cookie-profile",
        help="独立浏览器资料目录，可复用登录状态",
    )
    parser.add_argument("--wait-seconds", type=int, default=300, help="等待手动登录/验证的最长秒数")
    parser.add_argument("--channel", default="chrome", help="优先使用的浏览器 channel，例如 chrome 或 msedge")
    return parser.parse_args()


def is_douyin_cookie(cookie: dict) -> bool:
    domain = cookie.get("domain", "").lstrip(".").lower()
    return any(domain == allowed or domain.endswith(f".{allowed}") for allowed in COOKIE_DOMAINS)


def important_cookie_summary(cookies: list[dict]) -> tuple[list[str], list[str]]:
    present = {cookie.get("name", "") for cookie in cookies}
    found = sorted(name for name in IMPORTANT_COOKIE_NAMES if name in present)
    missing = sorted(name for name in IMPORTANT_COOKIE_NAMES if name not in present)
    return found, missing


def has_usable_cookie_set(found: list[str]) -> bool:
    found_set = set(found)
    has_browser_identity = {"s_v_web_id", "ttwid"}.issubset(found_set)
    has_fresh_web_tokens = bool({"msToken", "tt_scid"} & found_set)
    has_login_session = bool({"sessionid", "sessionid_ss"} & found_set)
    return has_browser_identity and (has_fresh_web_tokens or has_login_session)


def to_netscape_line(cookie: dict) -> str:
    domain = cookie.get("domain", "")
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path") or "/"
    secure = "TRUE" if cookie.get("secure") else "FALSE"
    expires_raw = cookie.get("expires")
    expires = 0 if expires_raw is None or expires_raw < 0 else int(expires_raw)
    name = cookie.get("name", "")
    value = cookie.get("value", "")
    if cookie.get("httpOnly") and not domain.startswith("#HttpOnly_"):
        domain = f"#HttpOnly_{domain}"
    return "\t".join([domain, include_subdomains, path, secure, str(expires), name, value])


def write_netscape_cookie_file(path: Path, cookies: list[dict]) -> None:
    lines = [
        "# Netscape HTTP Cookie File",
        f"# Generated by scripts/export-douyin-cookie.py at {dt.datetime.now(dt.timezone.utc).isoformat()}",
    ]
    lines.extend(to_netscape_line(cookie) for cookie in cookies)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    output_path = Path(args.output).resolve()
    profile_dir = Path(args.profile_dir).resolve()

    with sync_playwright() as p:
        launch_options = {"headless": False, "args": ["--start-maximized"]}
        try:
            context = p.chromium.launch_persistent_context(
                str(profile_dir), channel=args.channel, viewport=None, locale="zh-CN", **launch_options
            )
        except Exception:
            context = p.chromium.launch_persistent_context(
                str(profile_dir), viewport=None, locale="zh-CN", **launch_options
            )

        page = context.pages[0] if context.pages else context.new_page()
        print(f"[1] 打开 {args.url}", flush=True)
        page.goto(args.url, wait_until="domcontentloaded", timeout=60_000)
        print("[2] 如页面要求登录、扫码或验证，请在打开的浏览器中完成。", flush=True)

        deadline = time.monotonic() + max(30, args.wait_seconds)
        selected: list[dict] = []
        found: list[str] = []
        missing: list[str] = sorted(IMPORTANT_COOKIE_NAMES)
        reached_usable_set = False
        while time.monotonic() < deadline:
            page.wait_for_timeout(2_000)
            all_cookies = context.cookies([args.url, DOUYIN_URL])
            selected = [cookie for cookie in all_cookies if is_douyin_cookie(cookie)]
            found, missing = important_cookie_summary(selected)
            if len(selected) >= 8 and has_usable_cookie_set(found):
                reached_usable_set = True
                break

        if not selected:
            print("[!] 未捕获到抖音相关 Cookie，请确认浏览器页面已正常打开。", flush=True)
            context.close()
            return 1

        write_netscape_cookie_file(output_path, selected)
        print(f"[3] 已写入 {output_path}", flush=True)
        print(f"[4] 抖音 Cookie 数量：{len(selected)}", flush=True)
        print(f"[5] 关键字段已出现：{', '.join(found) if found else '无'}", flush=True)
        if missing:
            print(f"[6] 关键字段暂缺：{', '.join(missing)}", flush=True)
        if not reached_usable_set:
            print("[!] 未达到完整推荐 Cookie 组合，请先用 yt-dlp 验证该文件后再上传服务器。", flush=True)
            context.close()
            return 2
        print("[7] 浏览器会话已保留在 profile-dir，下次可复用或重新登录。", flush=True)
        context.close()
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
